FROM centos:7

run yum -y update
run yum -y install php httpd mysql php-mbstring php-xml

run wget http://ja.wordpress.org/latest-ja.tar.gz -P /tmp/
run tar zxvf /tmp/latest-ja.tar.gz -C /tmp
run cp -r /tmp/wordpress/* /var/www/html/
run chown apache:apache -R /var/www/html
